### ISSUE TITLE
Access to the Header

### ISSUE THREAD

**Issue by Kleak** [dart-lang/rpc#32]
Is there a way to acces to the header we receive and modify the header we send?

**Comment by wibling** [comment]
Currently this can only be done by writing your own http request handler and intercepting the request/response. You cannot as of now access the header inside the api method. I am working on issue 15 which should give you access to the request headers in the method.

**Comment by mmaquevice** [comment]
+1, i need this feature too ! 

And also the possibility to customize the status code returned by my method (201, 204... instead of 200), is it in the roadmap too ?

**Comment by wibling** [comment]
FYI with the latest version you now have access to the request url and headers in the "context." variable within your api methods.
Also I changed it such that there is a 'rpc/api.dart' file which should be used in the dart file(s) defining your api instead of 'rpc/rpc.dart'. This is not a requirement, but does mean you don't include server specific packages (dart:io) into your api code which can be a problem if shared.

**Comment by Kleak** [comment]
great :)
and what about custom status code and access to the header of the response?

**Comment by wibling** [comment]
Working on the remaining parts as well :)

**Comment by wibling** [comment]
Should be fixed as of 659ccabd6b6e91e06bf27f4f99f192fdd19b356a.
