### ISSUE TITLE
Auto-namespacing the APIMethods

### ISSUE THREAD

**Issue by FaisalAbid** [dart-lang/rpc#50]
If I have an API class and a few APIResources declared in it like so

`@ApiResource(name: 'user')
  UserResource user = new UserResource();`

`@ApiResource(name: 'movie')
  MovieResource user = new MovieResource();`

It would be good if inside UserResource or MovieResource I can just put

  `@ApiMethod(method: 'POST', path: 'register')
  Future<Map<String, String>> register(UserRequest request) async{`

rather than

  `@ApiMethod(method: 'POST', path: 'user/register')
  Future<Map<String, String>> register(UserRequest request) async{`

This way I can easily shuffle the resources around under different paths in the future without having to change the the path inside the resources.

**Comment by wibling** [comment]
Hi Faisal,

We deliberately decided to not have the HTTP path follow the nesting of the objects. The reason was that it was more flexible and also ensured that people were conscious about changes to the public HTTP REST API.
It does mean you have to update the path explicitly, but at the same time it gives the freedom to decouple the internal code layout from the external API layout, which can be quite useful, especially when the API grows big.

Cheers,
/gustav

**Comment by FaisalAbid** [comment]
Okay sure, I buy that. Makes sense to me.

Thanks!
