### ISSUE TITLE
pub run rpc:generate client fails silently

### ISSUE THREAD

**Issue by jkriesel** [dart-lang/rpc#99]
Is there a way to generate an error or understand why "pub run rpc:generate client [input] [output]" fails?  For some reason this stopped working, but I can't tell if it's an issue with the recent update or a change that I have made in my code.

As it stands to today, it just runs forever and never fails.

**Comment by jkriesel** [comment]
One approach to resolve this would be turn this call `var docsWithImports = await generator.generateDiscoveryWithImports();` into returning a future and handling both the complete and completeError events. 

Are there any objections to this approach?  I'll be happy to submit the code changes if there are no objections.

**Comment by mkustermann** [comment]
It is not entirely clear to me what the issue here is, but I found that the package did not surface errors correctly to the user (it rather blocks forever).

I've a CL out which should fix this part: https://codereview.chromium.org/2338233002

If this does not fix the original issue, I would like to ask you for some help reproducing this issue.

**Comment by mkustermann** [comment]
The CL has landed.

@jkriesel It would be great if you could report back if you get an error message now.

**Comment by jkriesel** [comment]
Thank you!  That does resolve the issue.
